flags: {}
extra-include-dirs:
- /usr/local/Cellar/icu4c/55.1/include
extra-package-dbs: []
extra-lib-dirs:
- /usr/local/Cellar/icu4c/55.1/lib
packages:
- '.'
extra-deps:
- text-1.2.2.1
- text-regex-replace-0.1.1.1
resolver: lts-5.13
